pipelines:
    custom:
        win32-installer:
            - step:
                name: InVEST User's Guide
                image: natcap/userguide-build:0da3dbeaf1aa3a7bb4b7bd583db9fea708e61709
                script:
                    - make userguide
                artifacts:
                    - dist/**
            - step:
                name: Archive Sample Data
                image: debian:9.7
                script:
                    - apt-get update && apt-get install -y subversion mercurial build-essential zip
                    - make sampledata
                artifacts:
                    - dist/**
                    - data/invest-test-data/*.json
            - step:
                name: InVEST Binaries
                image: natcap/py27-wine-build:d34b1377dbd1c6e77dfbae5c273bf84dbd0fc583
                script:
                    - wine make env
                    - wine env\scripts\python.exe -m pip install --upgrade .
                    - wine env\scripts\python.exe -m pip install -r requirements-gui.txt
                    - wine make PYTHON=env\scripts\python.exe binaries
                artifacts:
                    - dist/**
            - step:
                name: InVEST NSIS Installer
                image: natcap/py27-wine-build:d34b1377dbd1c6e77dfbae5c273bf84dbd0fc583
                script:
                    # First, need to put the vcredist into the right place (no powershell under WINE)
                    - make build
                    - wget -nv -O build/vcredist_x86.exe \
                        https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe
                    - wine python -m virtualenv --system-site-packages env
                    - wine env/Scripts/python -m pip install -r requirements.txt -r requirements-gui.txt
                    - wine env/Scripts/python -m pip install -I -r requirements-dev.txt
                    - wine make PYTHON=env/Scripts/python install
                    - wine make PYTHON=env/Scripts/python windows_installer
                artifacts:
                    - dist/**
    default:
        - parallel:
            - step:
                name: UI tests on WINE
                image: natcap/py27-wine-build:d34b1377dbd1c6e77dfbae5c273bf84dbd0fc583
                script:
                    - wine python -m virtualenv --system-site-packages env
                    - wine env/Scripts/python -m pip install -r requirements.txt -r requirements-gui.txt
                    - wine env/Scripts/python -m pip install -I -r requirements-dev.txt
                    - wine env/Scripts/python setup.py bdist_wheel
                    - wine env/Scripts/python -m pip install -I --no-deps dist/*.whl
                    - wine env/Scripts/python -m nose -vsP --with-coverage --with-timer --cover-package=natcap.invest ui_tests
            - step:
                name: Model tests on WINE
                image: natcap/py27-wine-build:d34b1377dbd1c6e77dfbae5c273bf84dbd0fc583
                script:
                    - make data/invest-test-data
                    - wine python -m virtualenv --system-site-packages env
                    - wine env/Scripts/python -m pip install -r requirements.txt -r requirements-gui.txt
                    - wine env/Scripts/python -m pip install -I -r requirements-dev.txt
                    - wine env/Scripts/python setup.py bdist_wheel
                    - wine env/Scripts/python -m pip install -I --no-deps dist/*.whl
                    - wine env/Scripts/python -m nose -vsP --with-coverage --with-timer --cover-package=natcap.invest tests
                artifacts:
                    - dist/*.whl
