pipelines:
    custom:
        win32-installer:
            - step:
                name: InVEST User's Guide
                image: natcap/userguide-build:0da3dbeaf1aa3a7bb4b7bd583db9fea708e61709
                script:
                    - make userguide
                artifacts:
                    - dist/**
            - step:
                name: Archive Sample Data
                image: debian:9.7
                script:
                    - apt-get update && apt-get install -y subversion mercurial build-essential zip
                    - make sampledata
                artifacts:
                    - dist/**
                    - data/invest-test-data/*.json
            - step:
                name: InVEST Binaries
                image: natcap/py27-wine-build:f8dbb1a79151859d0358cc9e645d339bae5b992d
                script:
                    - wget ftp://ftp.equation.com/make/32/make.exe
                    - export WINEDEBUG=fixme-all  # Filter out fixme logging from WINE
                    - wine pip install https://storage.googleapis.com/natcap-build-dependencies/windows/wheels-win32/PyQt4-4.11.4-cp27-cp27m-win32.whl
                    - wine make env
                    - wine env\scripts\python.exe -m pip install --upgrade .
                    - wine env\scripts\python.exe -m pip install -r requirements-gui.txt
                    - wine make PYTHON=env\scripts\python.exe binaries
                artifacts:
                    - dist/**
            - step:
                name: InVEST NSIS Installer
                image: natcap/nsis-build
                script:
                    - make installer
                artifacts:
                    - dist/**
            - step:
                name: Deploy to release bucket
                image: debian:stretch
                script:
                    - exit 1
    default:
        - parallel:
            - step:
                name: UI tests on WINE
                image: natcap/py27-wine-build:f8dbb1a79151859d0358cc9e645d339bae5b992d
                script:
                    - wget ftp://ftp.equation.com/make/32/make.exe
                    - export WINEDEBUG=fixme-all  # Filter out fixme logging from WINE
                    - wine pip install https://storage.googleapis.com/natcap-build-dependencies/windows/wheels-win32/PyQt4-4.11.4-cp27-cp27m-win32.whl
                    - wine pip install cython numpy setuptools_scm
                    - wine make jenkins_test_ui
            - step:
                name: Model tests on WINE
                image: natcap/py27-wine-build:f8dbb1a79151859d0358cc9e645d339bae5b992d
                script:
                    - apt-get update && apt-get install -y python-setuptools cython python-numpy
                      # Self-contained make binary, taken from scoop.sh 'package manager'
                    - wget ftp://ftp.equation.com/make/32/make.exe
                    - export WINEDEBUG=fixme-all  # Filter out fixme logging from WINE
                    - wine pip install cython numpy setuptools_scm
                    - make data/invest-test-data
                    - wine make jenkins_test_ui
