pipelines:
    options:
        max-time: 20
    custom:
        win32-installer:
            - parallel:
                - step:
                    name: User's Guide
                    image: natcap/userguide-build:fba743220031e1ba99b528a8939a86c8201da949
                    script:
                        # If setup.py --version fails, we'll get bad version
                        # info in the UG build.
                        - python setup.py --version
                        - make userguide
                    artifacts:
                        - dist/**
                - step:
                    name: Sample Data
                    image: debian:9.7
                    script:
                        - apt-get update && apt-get install -y subversion
                            mercurial build-essential zip python-setuptools
                            python-numpy python-setuptools-scm cython
                        - make sampledata
                    artifacts:
                        - dist/**
                        - data/invest-sample-data/*.json
                - step:
                    name: Python Binaries
                    image: natcap/py27-wine-build:d34b1377dbd1c6e77dfbae5c273bf84dbd0fc583
                    caches:
                        - pip
                    script:
                        - wine make env
                        - wine env/scripts/python.exe -m pip install --upgrade .
                        - wine env/scripts/python.exe -m pip install
                            -r requirements-gui.txt
                            -r requirements-dev.txt
                            -r requirements.txt
                        - wine make PYTHON=env/scripts/python.exe binaries
                    artifacts:
                        - dist/**
            - step:
                name: NSIS Installer
                image: natcap/py27-wine-build:d34b1377dbd1c6e77dfbae5c273bf84dbd0fc583
                script:
                    # First, need to put the vcredist into the right place (no powershell under WINE)
                    - make build
                    - wget -nv -O build/vcredist_x86.exe
                        https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe
                    - wine make windows_installer
                artifacts:
                    - dist/**
    default:
        - parallel:
            - step:
                name: Model tests on WINE
                image: natcap/py27-wine-build:d34b1377dbd1c6e77dfbae5c273bf84dbd0fc583
                max-time: 15
                script:
                    - make data/invest-test-data
                    - wine python -m virtualenv --system-site-packages env
                    - wine env/Scripts/python -m pip install -r requirements.txt -r requirements-gui.txt
                    - wine env/Scripts/python -m pip install -I -r requirements-dev.txt
                    - wine env/Scripts/python setup.py bdist_wheel
                    - wine env/Scripts/python -m pip install -I --no-deps dist/*.whl
                    - wine env/Scripts/python -m nose -vsP --with-coverage --with-timer --cover-package=natcap.invest tests
                artifacts:
                    - dist/*.whl
